# Example snippet for docker-compose.yml. Can be combined with pigallery2
version: "3"

  tesla-dashcam-manager:
    image: simonkagstrom/tesla_dashcam_manager
    restart: always
    environment:
        - TZ=Europe/Stockholm
        - TESLA_DASHCAM_ARGUMENTS=--title_screen_map --gpu --gpu_type=rpi --text_overlay_fmt "{event_timestamp} {event_city}"
        - RETAIN_DAYS=365
    devices:
        - "/dev/vchiq:/dev/vchiq"
    volumes:
        - "/mnt/staging:/app/staging"
        - "/mnt/raw-storage:/app/raw-storage"
        - "/mnt/photos/TeslaCam:/app/destination-path"
