# Example snippet for docker-compose.yml.
version: "3"

services:

## Example setup for pigallery2, pigallery2 can be accessed at port 5000 here
#  pigallery2:
#    image: bpatrik/pigallery2:1.9.0-alpine
#    container_name: pigallery2
#    privileged: true
#    environment:
#      - NODE_ENV=production
#    volumes:
#      - "/var/lib/pigallery2/config:/app/data/config"
#      - "pigallery-db-data:/app/data/db"
#      - "/mnt/photos:/app/data/images"
#      - "/tmp:/app/data/tmp"
#    ports:
#      - 5000:5000
#    restart: always

  tesla-dashcam-manager:
    image: simonkagstrom/tesla_dashcam_manager
    restart: always
    environment:
        - TZ=Europe/Stockholm
        - TESLA_DASHCAM_ARGUMENTS=--title_screen_map --gpu --gpu_type=rpi --text_overlay_fmt "{event_timestamp} {event_city}"
        - RETAIN_DAYS=365
    devices:
        - "/dev/vchiq:/dev/vchiq"
    volumes:
        - "/mnt/staging:/app/staging"
        - "/mnt/raw-storage:/app/raw-storage"
        - "/mnt/photos/TeslaCam:/app/destination-path"
